### PR TITLE
Fix visibility issues with events, nested types, and 'private protected'

### LINKED ISSUE #109: Private protected methods are not API
C# 7.2 exposed the `famandassem` visibility that .NET binaries have always supported: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/private-protected

(`protected internal` compiles to `famorassem`.)

For:

```cs
public class ClassWithPrivateProtectedMethod
{
    private protected void DoSomething()
    {
    }
}
```

ApiApprover generates:

```cs
namespace PublicApiGeneratorTests.Examples
{
    public class ClassWithPrivateProtectedMethod
    {
        public ClassWithPrivateProtectedMethod() { }
        void DoSomething() { }
    }
}
```

But `DoSomething` should not be visible.

PR incoming.

### PR DESCRIPTION
**Pull request by jnm2**
Fixes #109. 

I set out to fix `famandassem` members which should not be shown. They have been able to be created in .NET assemblies since the beginning.

While writing tests, I discovered that tests were missing for the visibility of events and nested `protected internal` types. I added them and they failed, so this PR fixes two additional issues:

- Events were being included and shown as `public` regardless of visibility, including private ones.
- Nested `protected internal` types were excluded even though they appear as `protected` types from outside the assembly.

### CODE REVIEW

File: src/PublicApiGeneratorTests/Event_visibility.cs [hunk 1]
```diff
@@ -0,0 +1,130 @@
+﻿using PublicApiGeneratorTests.Examples;
+using System;
+using Xunit;
+
+namespace PublicApiGeneratorTests
+{
+    public class Event_visibility :  ApiGeneratorTestsBase
```
Comment (jnm2) [inline src/PublicApiGeneratorTests/Event_visibility.cs]: This file is a direct copy of `Property_visibility` with a few search and replaces and with the tests of differing accessor visibility removed. (Event accessor visibility can differ in .NET assemblies but not in C#.)

File: src/PublicApiGenerator/ApiGenerator.cs [hunk 2]
```diff
@@ -721,10 +738,13 @@ static void AddPropertyToTypeDeclaration(CodeTypeDeclaration typeDeclaration, Pr
             var getterAttributes = member.GetMethod != null ? GetMethodAttributes(member.GetMethod) : 0;
             var setterAttributes = member.SetMethod != null ? GetMethodAttributes(member.SetMethod) : 0;
 
-            if (!HasVisiblePropertyMethod(getterAttributes) && !HasVisiblePropertyMethod(setterAttributes))
+            var hasGet = member.GetMethod is object && ShouldIncludeMember(getterAttributes);
+            var hasSet = member.SetMethod is object && ShouldIncludeMember(setterAttributes);
+
+            if (!(hasGet | hasSet))
```
Comment (sungam3r) [inline src/PublicApiGenerator/ApiGenerator.cs]: | or || ?

Comment (jnm2) [reply src/PublicApiGenerator/ApiGenerator.cs]: Happy to change to suit your preference. My habit is `|` unless there is a chance of skipping any work. `||` is more to type and introduces a branch.

Comment (sungam3r) [reply src/PublicApiGenerator/ApiGenerator.cs]: It does not matter

**Comment by danielmarbach** [comment]
@jnm2 this probably requires a rebase on top of master

**Comment by jnm2** [comment]
Rebased. This one was tricky to untangle. I think I did it right, but shout if something looks off!

File: src/PublicApiGenerator/CecilEx.cs [hunk 3]
```diff
@@ -58,41 +58,33 @@ public static bool IsCompilerGenerated(this IMemberDefinition m)
...
 
-        public static bool HasVisiblePropertyMethod(this MemberAttributes attributes)
-        {
-            var access = attributes & MemberAttributes.AccessMask;
-            return access == MemberAttributes.Public ||
-                   access == MemberAttributes.Family ||
-                   access == MemberAttributes.FamilyOrAssembly;
-        }
-
-        public static MemberAttributes GetPropertyAttributes(MemberAttributes getterAttributes, MemberAttributes setterAttributes)
```
Comment (danielmarbach) [inline src/PublicApiGenerator/CecilEx.cs]: Thinking out loud. Should this be an extension method on the first param because it is placed in an extension file?

Comment (jnm2) [reply src/PublicApiGenerator/CecilEx.cs]: Not sure I know the answer, good question.

Comment (sungam3r) [reply src/PublicApiGenerator/CecilEx.cs]: Technically, there is no concept of an _extension file_ or even an _extension class_. There is an _extension method_. And it can be located in any static class. In addition, even the class itself is not called Cecil**Extensions**.
